link:
  -
    judul: Facebook
    link: http://facebook.com/mzaini30
    icon: facebook-square
  -
    judul: 10 Fast Fingers
    link: https://10fastfingers.com/user/1452563/
    icon: keyboard-o
  -
    judul: Github
    link: http://github.com/mzaini30
    icon: github
  -
    judul: Play Store
    link: http://github.com/mzaini30
    icon: android