# penghargaan

penghargaan:
  -
    tahun: 2018 
    judul: Mahasiswa Berprestasi
    link: https://s25.postimg.org/shsyq8a6n/Scan352.jpg
    tingkat: Prodi
  -
    tahun: 2017 
    judul: 'Peserta: Sosialisasi 4 Pilar MPR RI'
    link: https://s25.postimg.org/5gcdkhi8v/Scan351.jpg
    tingkat: Nasional
  -
    tahun: 2017 
    judul: 'Panitia: Rakoornas ILMPI'
    link: https://s25.postimg.org/8afixx4zj/Scan355.jpg
    tingkat: Nasional
  -
    tahun: 2016 
    judul: 'Peserta: Workshop Grafologi'
    link: https://s25.postimg.org/k1z9eqwf3/gambar_0002.jpg
    tingkat: Prodi
  -
    tahun: 2014 
    judul: 'Finalis: Web Desain'
    link: https://s25.postimg.org/oal5eau9r/Desain_web.jpg
    tingkat: Nasional
  -
    tahun: 2014 
    judul: 'Desain Terkreatif dan Inovatif: Web Desain'
    link: https://s25.postimg.org/clzzszban/gambar_0004.jpg
    tingkat: Nasional
  -
    tahun: 2013 
    judul: 'Juara 2: Lomba Blog'
    link: https://s25.postimg.org/nyclarrpb/gambar_0006.jpg
    tingkat: Eks Karisidenan Surakarta
  -
    tahun: 2012 
    judul: 'Peserta: Lomba Kimia'
    link: https://s25.postimg.org/hww2b24tb/Kimia.jpg
    tingkat: Eks Karisidenan Surakarta
  -
    tahun: 2012 
    judul: 'Juara 2: Pidato Bahasa Indonesia'
    link: https://s25.postimg.org/qf5ifeyhb/Pidato_bahasa_indonesia_2.jpg
    tingkat: Mahad
  -
    tahun: 2012 
    judul: 'Juara 2: Lomba Karya Tulis Ilmiah'
    link: https://s25.postimg.org/3qz5iic8f/gambar_0009.jpg
    tingkat: Mahad
  -
    tahun: 2012 
    judul: 'Juara 2: Karya Tulis'
    link: https://s25.postimg.org/5v0ogx3an/Karya_tulis.jpg
    tingkat: Mahad
  -
    tahun: 2012 
    judul: 'Juara 1: Cerdas Cermat'
    link: https://s25.postimg.org/h7d9yntz3/Cerdas_cermat.jpg
    tingkat: Mahad
  -
    tahun: 2011 
    judul: 'Peserta: Pidato Bahasa Indonesia'
    link: https://s25.postimg.org/4fz3s6mrz/Pidato_bahasa_indonesia.jpg
    tingkat: Eks Karisidenan Surakarta
  -
    tahun: 2010 
    judul: 'Juara Harapan 1: Asah Terampil Matematika'
    link: https://s25.postimg.org/jcgh2fllr/gambar_0001.jpg
    tingkat: Provinsi
  -
    tahun: 2010 
    judul: 'Juara 1: Lomba Blog'
    link: https://s25.postimg.org/tzaa7v96n/gambar_0005.jpg
    tingkat: Sekolah
  -
    tahun: 2009 
    judul: 'Peserta: Olimpiade Matematika'
    link: https://s25.postimg.org/doa6bkrjz/gambar_0011.jpg
    tingkat: Nasional
  -
    tahun: 2009 
    judul: 'Peserta: Asah Terampil Matematika'
    link: https://s25.postimg.org/rupx6qa3z/gambar_0003.jpg
    tingkat: Provinsi
  -
    tahun: 2008 
    judul: 'Juara 2: Lomba Pidato Bahasa Inggris'
    link: https://s25.postimg.org/9f5g9c3pb/gambar_0010.jpg
    tingkat: Kota
  -
    tahun: 2006 
    judul: 'Juara 1: Lomba Kaligrafi'
    link: https://s25.postimg.org/fsujcn61b/gambar_0008.jpg
    tingkat: Kota
  -
    tahun: 2004 
    judul: 'Juara 2: Lomba Hapalan Juz Amma'
    link: https://s25.postimg.org/5vjijk3kf/gambar_0007.jpg
    tingkat: Kota

# aplikasi android

aplikasi_android:
  -
    link: https://play.google.com/store/apps/details?id=com.mzaini30.coffeescript
    gambar: https://s25.postimg.org/600rg1tin/Screenshot_2018-03-10-15-09-22.jpg
  -
    link: https://play.google.com/store/apps/details?id=com.mzaini30.ecmascript
    gambar: https://s25.postimg.org/j46bsp3jz/Screenshot_2018-03-10-15-09-44.jpg
  -
    link: https://play.google.com/store/apps/details?id=com.mzaini30.font
    gambar: https://s25.postimg.org/anj80qj0f/Screenshot_2018-03-03-16-12-15.jpg
  -
    link: https://play.google.com/store/apps/details?id=com.mzaini30.hurufjepang
    gambar: https://s25.postimg.org/ly9h5q5lr/Screenshot_2018-03-10-15-10-11.jpg
  -
    link: https://play.google.com/store/apps/details?id=com.mzaini30.japanstory
    gambar: https://s25.postimg.org/5z4lrtt9b/Screenshot_2018-03-11-07-12-50.jpg
  -
    link: https://play.google.com/store/apps/details?id=com.mzaini30.kaligrafi
    gambar: https://s25.postimg.org/xozt6gnsv/Screenshot_2018-03-03-16-12-53.jpg
  -
    link: https://play.google.com/store/apps/details?id=com.mzaini30.materializecolor
    gambar: https://s25.postimg.org/6eehyixqn/Screenshot_2018-03-03-16-13-07.jpg
  -
    link: https://play.google.com/store/apps/details?id=com.mzaini30.psikologiuniversitasmulawarman
    gambar: https://s25.postimg.org/8vq95s27j/Screenshot_2018-03-03-16-14-37.jpg
  -
    link: https://play.google.com/store/apps/details?id=com.mzaini30.puasa2018
    gambar: https://s25.postimg.org/9y0foaxvj/Screenshot_2018-03-03-16-14-57.jpg
  -
    link: https://play.google.com/store/apps/details?id=com.mzaini30.seindahsunnah
    gambar: https://s25.postimg.org/3x2qr7o3z/Screenshot_2018-03-03-16-15-19.jpg
  -
    link: https://play.google.com/store/apps/details?id=com.mzaini30.sekolahimpian
    gambar: https://s25.postimg.org/kxlmzvlpr/Screenshot_2018-03-03-16-15-29.jpg
  -
    link: https://play.google.com/store/apps/details?id=com.mzaini30.tutorialjade
    gambar: https://s25.postimg.org/f7szwkstb/Screenshot_2018-03-10-15-09-09.jpg
  -
    link: https://play.google.com/store/apps/details?id=com.mzaini30.zen
    gambar: https://s25.postimg.org/bptej5jsf/Screenshot_2018-03-03-16-15-44.jpg

# aplikasi web

aplikasi_web:
  -
    link: /font
    gambar: https://s25.postimg.org/4vvgoyr3z/Screenshot_from_2018-02-02_14_44_14.png
  -
    link: /jumlah-satuan
    gambar: https://s25.postimg.org/pav5ryxov/Screenshot_from_2018-02-20_00_20_37.png
  -
    link: /kaligrafi
    gambar: https://s25.postimg.org/et6hi5w6n/Screenshot_from_2018-02-02_14_49_18.png
  -
    link: /kontest
    gambar: https://s25.postimg.org/z1p9q3gdr/Screenshot_from_2018-02-02_09_21_26.png
  -
    link: /kontur
    gambar: https://s25.postimg.org/mpvk3zru7/Screenshot_from_2018-02-02_16_46_04.png
  -
    link: /color30
    gambar: https://s25.postimg.org/ormuqxitb/Screenshot_from_2018-02-02_09_29_56.png
  -
    link: /tambah-hari
    gambar: https://s25.postimg.org/x0np8974v/Screenshot_from_2018-02-17_14_04_27.png
  -
    link: /wa
    gambar: https://s25.postimg.org/4x0t4svvz/Screenshot_from_2018-02-02_09_27_13.png