# settingan dasar

url: http://desain-tema-jekyll.github.io
lokasi: '/media/data/web/desain-tema-jekyll.github.io (git)'
permalink: /:year/:month/:day/:title.html
title: Zen
description: Psikologi

# paginate

paginate: 12

# pengumuman

# pengumuman:
#   isi: Tes
#   jenis: danger # info, success, warning, danger

# iklan

harga_iklan: '1.003'
slot_iklan:
  -
    berlaku_hingga: ''
    link: 'https://api.whatsapp.com/send?phone=6281545143654&text=Assalamualaikum%20Kak%20Zen.%20Saya%20ingin%20memasang%20iklan%20di%20blog%20Kak%20Zen'
    gambar: 'https://s25.postimg.org/qxxoz423z/slot_iklan_2.png'
  -
    berlaku_hingga: ''
    link: 'https://api.whatsapp.com/send?phone=6281545143654&text=Assalamualaikum%20Kak%20Zen.%20Saya%20ingin%20memasang%20iklan%20di%20blog%20Kak%20Zen'
    gambar: 'https://s25.postimg.org/qxxoz423z/slot_iklan_2.png'
  -
    berlaku_hingga: ''
    link: 'https://api.whatsapp.com/send?phone=6281545143654&text=Assalamualaikum%20Kak%20Zen.%20Saya%20ingin%20memasang%20iklan%20di%20blog%20Kak%20Zen'
    gambar: 'https://s25.postimg.org/qxxoz423z/slot_iklan_2.png'
  -
    berlaku_hingga: ''
    link: 'https://api.whatsapp.com/send?phone=6281545143654&text=Assalamualaikum%20Kak%20Zen.%20Saya%20ingin%20memasang%20iklan%20di%20blog%20Kak%20Zen'
    gambar: 'https://s25.postimg.org/qxxoz423z/slot_iklan_2.png'

# gambar default

gambar: https://img00.deviantart.net/e121/i/2017/198/c/2/fate_apocrypha_hd_wallpaper_by_tammypain-dbgp3hz.png

# stay connected

stay_connected:
  -
    judul: Github
    link: http://github.com/mzaini30
  -
    judul: Facebook
    link: http://facebook.com/mzaini30
  -
    judul: Telegram
    link: http://t.me/mzaini30a
  -
    judul: Whatsapp
    link: https://api.whatsapp.com/send?phone=6281545143654
  -
    judul: Play Store
    link: 

# blogwalking

blogwalking:
  -
    judul: Ikatan Lembaga Mahasiswa Psikologi Indonesia
    link: http://ilmpi.org/
  -
    judul: Isy Karima
    link: https://www.youtube.com/channel/UCXX1KQrPS2tFsKkvPcHcTUw/videos
  -
    judul: Himpunan Psikologi Indonesia
    link: http://himpsi.or.id/
  -
    judul: American Psychological Association
    link: http://www.apa.org/
  -
    judul: Medium
    link: https://medium.com/
  -
    judul: Electronic Frontier Foundation
    link: https://www.eff.org/
  -
    judul: Free Code Camp
    link: https://medium.freecodecamp.org/
  -
    judul: Qonita
    link: http://qnitaaa.blogspot.co.id/
  -
    judul: Dewie Dean
    link: http://dewieajaa.blogspot.co.id/
  -
    judul: Heni Puspita
    link: http://www.henipuspita.net/
  -
    judul: Nova Nodiwa
    link: https://www.nodiwa.com/
  -
    judul: Rian Yulianto W
    link: https://medium.com/@kucingmeongs
  -
    judul: Rani Psikologi
    link: https://www.wattpad.com/user/hasannahrani
  -
    judul: Dewi Sampurna Wati
    link: https://www.wattpad.com/user/dewisampurnaw
  -
    judul: Japanese Station
    link: https://japanesestation.com/
  -
    judul: My Satnite
    link: https://www.mysatnite.com/
  -
    judul: Syufia
    link: http://syufiayaumma.blogspot.co.id/
  -
    judul: Kompi Teknologi Indonesia
    link: http://www.kompitech.me/
  -
    judul: Codepolitan
    link: https://www.codepolitan.com/articles
  -
    judul: Petani Kode
    link: https://www.petanikode.com/

# penghargaan

penghargaan:
  -
    tahun: 2018 
    judul: "Kecepatan Mengetik: 85 Kata per Menit"
    link: https://10fastfingers.com/user/1452563/
    tingkat: Internasional
  -
    tahun: 2018 
    judul: Mahasiswa Berprestasi
    link: https://s25.postimg.org/shsyq8a6n/Scan352.jpg
    tingkat: Prodi
  -
    tahun: 2017 
    judul: 'Peserta: Sosialisasi 4 Pilar MPR RI'
    link: https://s25.postimg.org/5gcdkhi8v/Scan351.jpg
    tingkat: Nasional
  -
    tahun: 2017 
    judul: 'Panitia: Rakoornas ILMPI'
    link: https://s25.postimg.org/8afixx4zj/Scan355.jpg
    tingkat: Nasional
  -
    tahun: 2016 
    judul: 'Peserta: Workshop Grafologi'
    link: https://s25.postimg.org/k1z9eqwf3/gambar_0002.jpg
    tingkat: Prodi
  -
    tahun: 2014 
    judul: 'Finalis: Web Desain'
    link: https://s25.postimg.org/oal5eau9r/Desain_web.jpg
    tingkat: Nasional
  -
    tahun: 2014 
    judul: 'Desain Terkreatif dan Inovatif: Web Desain'
    link: https://s25.postimg.org/clzzszban/gambar_0004.jpg
    tingkat: Nasional
  -
    tahun: 2013 
    judul: 'Juara 2: Lomba Blog'
    link: https://s25.postimg.org/nyclarrpb/gambar_0006.jpg
    tingkat: Eks Karisidenan Surakarta
  -
    tahun: 2012 
    judul: 'Peserta: Lomba Kimia'
    link: https://s25.postimg.org/hww2b24tb/Kimia.jpg
    tingkat: Eks Karisidenan Surakarta
  -
    tahun: 2012 
    judul: 'Juara 2: Pidato Bahasa Indonesia'
    link: https://s25.postimg.org/qf5ifeyhb/Pidato_bahasa_indonesia_2.jpg
    tingkat: Mahad
  -
    tahun: 2012 
    judul: 'Juara 2: Lomba Karya Tulis Ilmiah'
    link: https://s25.postimg.org/3qz5iic8f/gambar_0009.jpg
    tingkat: Mahad
  -
    tahun: 2012 
    judul: 'Juara 2: Karya Tulis'
    link: https://s25.postimg.org/5v0ogx3an/Karya_tulis.jpg
    tingkat: Mahad
  -
    tahun: 2012 
    judul: 'Juara 1: Cerdas Cermat'
    link: https://s25.postimg.org/h7d9yntz3/Cerdas_cermat.jpg
    tingkat: Mahad
  -
    tahun: 2011 
    judul: 'Peserta: Pidato Bahasa Indonesia'
    link: https://s25.postimg.org/4fz3s6mrz/Pidato_bahasa_indonesia.jpg
    tingkat: Eks Karisidenan Surakarta
  -
    tahun: 2010 
    judul: 'Juara Harapan 1: Asah Terampil Matematika'
    link: https://s25.postimg.org/jcgh2fllr/gambar_0001.jpg
    tingkat: Provinsi
  -
    tahun: 2010 
    judul: 'Juara 1: Lomba Blog'
    link: https://s25.postimg.org/tzaa7v96n/gambar_0005.jpg
    tingkat: Sekolah
  -
    tahun: 2009 
    judul: 'Peserta: Olimpiade Matematika'
    link: https://s25.postimg.org/doa6bkrjz/gambar_0011.jpg
    tingkat: Nasional
  -
    tahun: 2009 
    judul: 'Peserta: Asah Terampil Matematika'
    link: https://s25.postimg.org/rupx6qa3z/gambar_0003.jpg
    tingkat: Provinsi
  -
    tahun: 2008 
    judul: 'Juara 2: Lomba Pidato Bahasa Inggris'
    link: https://s25.postimg.org/9f5g9c3pb/gambar_0010.jpg
    tingkat: Kota
  -
    tahun: 2006 
    judul: 'Juara 1: Lomba Kaligrafi'
    link: https://s25.postimg.org/fsujcn61b/gambar_0008.jpg
    tingkat: Kota
  -
    tahun: 2004 
    judul: 'Juara 2: Lomba Hapalan Juz Amma'
    link: https://s25.postimg.org/5vjijk3kf/gambar_0007.jpg
    tingkat: Kota

# aplikasi web

aplikasi_web:
  -
    link: /font
    gambar: https://s25.postimg.org/4vvgoyr3z/Screenshot_from_2018-02-02_14_44_14.png
    judul: Font
  -
    link: /jumlah-satuan
    gambar: https://s25.postimg.org/pav5ryxov/Screenshot_from_2018-02-20_00_20_37.png
    judul: Jumlah Satuan
  -
    link: /kaligrafi
    gambar: https://s25.postimg.org/et6hi5w6n/Screenshot_from_2018-02-02_14_49_18.png
    judul: Kaligrafi
  -
    link: /kontest
    gambar: https://s25.postimg.org/z1p9q3gdr/Screenshot_from_2018-02-02_09_21_26.png
    judul: Kontest
  -
    link: /kontur
    gambar: https://s25.postimg.org/mpvk3zru7/Screenshot_from_2018-02-02_16_46_04.png
    judul: Kontur
  -
    link: /color30
    gambar: https://s25.postimg.org/ormuqxitb/Screenshot_from_2018-02-02_09_29_56.png
    judul: Materialize Color
  -
    link: http://psikoweb.epizy.com/login/index.php
    gambar: https://s25.postimg.org/70kyy0y9r/Screenshot_from_2018-03-26_15_26_29.png
    judul: Psikoweb
  -
    link: /tambah-hari
    gambar: https://s25.postimg.org/x0np8974v/Screenshot_from_2018-02-17_14_04_27.png
    judul: Tambah Hari
  -
    link: /wa
    gambar: https://s25.postimg.org/4x0t4svvz/Screenshot_from_2018-02-02_09_27_13.png
    judul: Whatsapp Link Generator
